spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 这里面的nacos地址是你自己的nacos-server的地址
        enabled: true
        service: ${spring.application.name}
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
    props:
      sql:
        show: true
    sharding:
      tables:
        user:
          actualDataNodes: ds0.user$->{0..9}
          tableStrategy:
            inline:
              shardingColumn: id
              algorithmExpression: user$->{id % 10}
server:
  port: 7001
ribbon:
  ConnectTimeout: 50000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 50000 #请求处理的超时时间