
spring:
  application:
    name: order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # 这里面的nacos地址是你自己的nacos-server的地址
        enabled: true
        service: ${spring.application.name}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
server:
  port: 7002
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
ribbon:
  ConnectTimeout: 50000 #请求连接的超时时间，默认时间为1秒
  ReadTimeout: 50000 #请求处理的超时时间
feign:
  sentinel:
    enabled: true
seata:
  application-id: ${spring.application.name}
  tx-service-group: my_test_tx_group
  enable-auto-data-source-proxy: true
  service:
    vgroup-mapping:
      my_test_tx_group: default
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace:
      username: nacos
      password: nacos

